
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake-4.2.1/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/usr/bin/"
      - "/cygdrive/c/Program Files/PowerShell/7/"
      - "/cygdrive/c/Program Files/Microsoft/jdk-11.0.31.11-hotspot/bin/"
      - "/cygdrive/c/Windows/System32/"
      - "/cygdrive/c/Windows/"
      - "/cygdrive/c/Program Files/Common Files/Oracle/Java/javapath/"
      - "/cygdrive/c/usr/Ruby32-x64/bin/"
      - "/cygdrive/c/Windows/System32/wbem/"
      - "/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0/"
      - "/cygdrive/c/Windows/System32/OpenSSH/"
      - "/cygdrive/c/Program Files/dotnet/"
      - "/cygdrive/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/"
      - "/cygdrive/c/Program Files/Microsoft SQL Server/150/Tools/Binn/"
      - "/cygdrive/c/Program Files (x86)/Google/Cloud SDK/google-cloud-sdk/bin/"
      - "/cygdrive/c/Users/samue/AppData/Roaming/nvm/"
      - "/cygdrive/c/usr/nodejs/"
      - "/cygdrive/c/Program Files/Microsoft VS Code/bin/"
      - "/cygdrive/c/Program Files/Meld/"
      - "/cygdrive/c/Program Files/doxygen/bin/"
      - "/cygdrive/c/tools/TinyTeX/bin/windows/"
      - "/cygdrive/c/ProgramData/chocolatey/bin/"
      - "/cygdrive/c/Program Files/Microsoft SQL Server/170/Tools/Binn/"
      - "/cygdrive/c/Program Files/Pandoc/"
      - "/cygdrive/c/Program Files/Git/cmd/"
      - "/cygdrive/c/Program Files/GnuPG/bin/"
      - "/cygdrive/c/Program Files/CMake/bin/"
      - "/cygdrive/c/Program Files/Go/bin/"
      - "/cygdrive/c/Program Files/PuTTY/"
      - "/cygdrive/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
      - "/cygdrive/c/Program Files/GitHub CLI/"
      - "/cygdrive/c/PROGRA~1/CMake/bin/"
      - "/cygdrive/c/Users/samue/AppData/Local/Programs/Python/Launcher/"
      - "/cygdrive/c/usr/Java/jdk-22/bin/"
      - "/cygdrive/c/usr/Python/Python313/Scripts/"
      - "/cygdrive/c/usr/Python/Python311/Scripts/"
      - "/cygdrive/c/usr/Python/Python311/"
      - "/cygdrive/c/Users/samue/AppData/Local/Programs/Python/Python39/Scripts/"
      - "/cygdrive/c/Users/samue/AppData/Local/Programs/Python/Python39/"
      - "/cygdrive/c/Users/samue/.cargo/bin/"
      - "/cygdrive/c/Users/samue/AppData/Local/Microsoft/WindowsApps/"
      - "/cygdrive/c/Users/samue/.dotnet/tools/"
      - "/cygdrive/c/usr/bin/"
      - "/cygdrive/c/Users/samue/AppData/Local/JetBrains/Toolbox/scripts/"
      - "/cygdrive/c/Users/samue/AppData/Local/Microsoft/WinGet/Packages/GNU.Nano_Microsoft.Winget.Source_8wekyb3d8bbwe/"
      - "/cygdrive/c/usr/msys64/"
      - "/cygdrive/c/PROGRA~1/7-Zip/"
      - "/cygdrive/c/usr/flutter/bin/"
      - "/cygdrive/c/usr/flutter/"
      - "/cygdrive/c/usr/LLVM/bin/"
      - "/cygdrive/c/usr/win_flex_bison-latest/"
      - "/cygdrive/c/usr/php/latest/"
      - "/cygdrive/c/usr/dependencies-x64/"
      - "/cygdrive/c/Users/samue/AppData/Local/Microsoft/WinGet/Packages/Hugo.Hugo.Extended_Microsoft.Winget.Source_8wekyb3d8bbwe/"
      - "/cygdrive/c/usr/mpv/"
      - "/cygdrive/c/Users/samue/AppData/Local/Programs/VSCodium/bin/"
      - "/cygdrive/c/PROGRA~1/Graphviz/bin/"
      - "/cygdrive/c/usr/apache-maven/bin/"
      - "/cygdrive/c/Users/samue/AppData/Local/Microsoft/WinGet/Packages/DenoLand.Deno_Microsoft.Winget.Source_8wekyb3d8bbwe/"
      - "/cygdrive/c/usr/nginx/"
      - "/cygdrive/c/usr/PostgreSQL/16/bin/"
      - "/cygdrive/c/usr/PostgreSQL/16/lib/"
      - "/cygdrive/c/Users/samue/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin/"
      - "/cygdrive/c/Users/samue/AppData/Local/Microsoft/WinGet/Packages/zufuliu.notepad4_Microsoft.Winget.Source_8wekyb3d8bbwe/"
      - "/cygdrive/c/Users/samue/AppData/Local/Programs/Ollama/"
      - "/cygdrive/c/Users/samue/AppData/Local/Microsoft/WinGet/Packages/charmbracelet.glow_Microsoft.Winget.Source_8wekyb3d8bbwe/glow_2.1.2_Windows_x86_64/"
      - "/cygdrive/c/Users/samue/go/bin/"
      - "/cygdrive/c/Users/samue/AppData/Local/Microsoft/WinGet/Packages/waterlan.dos2unix_Microsoft.Winget.Source_8wekyb3d8bbwe/bin/"
      - "/bin/"
      - "/usr/local/bin/"
    searched_directories:
      - "/usr/bin/uname.com"
    found: "/usr/bin/uname.exe"
    search_context:
      ENV{PATH}:
        - "/usr/bin"
        - "/cygdrive/c/Program Files/PowerShell/7"
        - "/cygdrive/c/Program Files/Microsoft/jdk-11.0.31.11-hotspot/bin"
        - "/cygdrive/c/Windows/System32"
        - "/cygdrive/c/Windows"
        - "/cygdrive/c/Program Files/Common Files/Oracle/Java/javapath"
        - "/cygdrive/c/usr/Ruby32-x64/bin"
        - "/cygdrive/c/Windows/System32/wbem"
        - "/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0"
        - "/cygdrive/c/Windows/System32/OpenSSH"
        - "/cygdrive/c/Program Files/dotnet"
        - "/cygdrive/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn"
        - "/cygdrive/c/Program Files/Microsoft SQL Server/150/Tools/Binn"
        - "/cygdrive/c/Program Files (x86)/Google/Cloud SDK/google-cloud-sdk/bin"
        - "/cygdrive/c/Users/samue/AppData/Roaming/nvm"
        - "/cygdrive/c/usr/nodejs"
        - "/cygdrive/c/Program Files/Microsoft VS Code/bin"
        - "/cygdrive/c/Program Files/Meld"
        - "/cygdrive/c/Program Files/doxygen/bin"
        - "/cygdrive/c/tools/TinyTeX/bin/windows"
        - "/cygdrive/c/ProgramData/chocolatey/bin"
        - "/cygdrive/c/Program Files/Microsoft SQL Server/170/Tools/Binn"
        - "/cygdrive/c/Program Files/PowerShell/7"
        - "/cygdrive/c/Program Files/Pandoc"
        - "/cygdrive/c/Program Files/Git/cmd"
        - "/cygdrive/c/Program Files/GnuPG/bin"
        - "/cygdrive/c/Program Files/CMake/bin"
        - "/cygdrive/c/Program Files/Go/bin"
        - "/cygdrive/c/Program Files/PuTTY"
        - "/cygdrive/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit"
        - "/cygdrive/c/Program Files/GitHub CLI"
        - "/cygdrive/c/PROGRA~1/CMake/bin"
        - "/cygdrive/c/Users/samue/AppData/Local/Programs/Python/Launcher"
        - "/cygdrive/c/usr/Java/jdk-22/bin"
        - "/cygdrive/c/usr/Python/Python313/Scripts"
        - "/cygdrive/c/usr/Python/Python311/Scripts"
        - "/cygdrive/c/usr/Python/Python311"
        - "/cygdrive/c/Users/samue/AppData/Local/Programs/Python/Python39/Scripts"
        - "/cygdrive/c/Users/samue/AppData/Local/Programs/Python/Python39"
        - "/cygdrive/c/Users/samue/.cargo/bin"
        - "/cygdrive/c/Users/samue/AppData/Local/Microsoft/WindowsApps"
        - "/cygdrive/c/Users/samue/.dotnet/tools"
        - "/cygdrive/c/usr/bin"
        - "/cygdrive/c/Users/samue/AppData/Local/Programs/Python/Python39"
        - "/cygdrive/c/Users/samue/AppData/Local/Programs/Python/Python39/Scripts"
        - "/cygdrive/c/Users/samue/AppData/Local/JetBrains/Toolbox/scripts"
        - "/cygdrive/c/Users/samue/AppData/Roaming/nvm"
        - "/cygdrive/c/usr/nodejs"
        - "/cygdrive/c/Users/samue/AppData/Local/Microsoft/WinGet/Packages/GNU.Nano_Microsoft.Winget.Source_8wekyb3d8bbwe"
        - "/cygdrive/c/usr/msys64"
        - "/cygdrive/c/PROGRA~1/7-Zip"
        - "/cygdrive/c/usr/flutter/bin"
        - "/cygdrive/c/usr/flutter"
        - "/cygdrive/c/usr/LLVM/bin"
        - "/cygdrive/c/usr/win_flex_bison-latest"
        - "/cygdrive/c/usr/php/latest"
        - "/cygdrive/c/usr/dependencies-x64"
        - "/cygdrive/c/Users/samue/AppData/Local/Microsoft/WinGet/Packages/Hugo.Hugo.Extended_Microsoft.Winget.Source_8wekyb3d8bbwe"
        - "/cygdrive/c/usr/mpv"
        - "/cygdrive/c/Users/samue/AppData/Local/Microsoft/WindowsApps"
        - "/cygdrive/c/Users/samue/AppData/Local/Programs/VSCodium/bin"
        - "/cygdrive/c/PROGRA~1/Graphviz/bin"
        - "/cygdrive/c/usr/apache-maven/bin"
        - "/cygdrive/c/Users/samue/AppData/Local/Microsoft/WinGet/Packages/DenoLand.Deno_Microsoft.Winget.Source_8wekyb3d8bbwe"
        - "/cygdrive/c/usr/nginx"
        - "/cygdrive/c/usr/PostgreSQL/16/bin"
        - "/cygdrive/c/usr/PostgreSQL/16/lib"
        - "/cygdrive/c/tools/TinyTeX/bin/windows"
        - "/cygdrive/c/Users/samue/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin"
        - "/cygdrive/c/Users/samue/AppData/Local/Microsoft/WinGet/Packages/zufuliu.notepad4_Microsoft.Winget.Source_8wekyb3d8bbwe"
        - "/cygdrive/c/Users/samue/AppData/Local/Programs/Ollama"
        - "/cygdrive/c/Users/samue/AppData/Local/Microsoft/WinGet/Packages/charmbracelet.glow_Microsoft.Winget.Source_8wekyb3d8bbwe/glow_2.1.2_Windows_x86_64"
        - "/cygdrive/c/Users/samue/.dotnet/tools"
        - "/cygdrive/c/Users/samue/go/bin"
        - "/cygdrive/c/Users/samue/AppData/Local/Microsoft/WinGet/Packages/waterlan.dos2unix_Microsoft.Winget.Source_8wekyb3d8bbwe/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-4.2.1/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: CYGWIN - 3.6.9-1.x86_64 - x86_64
...
