# CMake generated Testfile for 
# Source directory: /Users/pkz/s2n
# Build directory: /Users/pkz/s2n
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(s2n_3des_test "/Users/pkz/s2n/bin/s2n_3des_test")
set_tests_properties(s2n_3des_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_aead_aes_test "/Users/pkz/s2n/bin/s2n_aead_aes_test")
set_tests_properties(s2n_aead_aes_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_aead_chacha20_poly1305_test "/Users/pkz/s2n/bin/s2n_aead_chacha20_poly1305_test")
set_tests_properties(s2n_aead_chacha20_poly1305_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_aes_sha_composite_test "/Users/pkz/s2n/bin/s2n_aes_sha_composite_test")
set_tests_properties(s2n_aes_sha_composite_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_aes_test "/Users/pkz/s2n/bin/s2n_aes_test")
set_tests_properties(s2n_aes_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_array_test "/Users/pkz/s2n/bin/s2n_array_test")
set_tests_properties(s2n_array_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_asn1_time_test "/Users/pkz/s2n/bin/s2n_asn1_time_test")
set_tests_properties(s2n_asn1_time_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_auth_selection_test "/Users/pkz/s2n/bin/s2n_auth_selection_test")
set_tests_properties(s2n_auth_selection_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_bike_r1_kat_test "/Users/pkz/s2n/bin/s2n_bike_r1_kat_test")
set_tests_properties(s2n_bike_r1_kat_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_bike_r1_kem_test "/Users/pkz/s2n/bin/s2n_bike_r1_kem_test")
set_tests_properties(s2n_bike_r1_kem_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_bike_r2_kat_test "/Users/pkz/s2n/bin/s2n_bike_r2_kat_test")
set_tests_properties(s2n_bike_r2_kat_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_bike_r2_kem_test "/Users/pkz/s2n/bin/s2n_bike_r2_kem_test")
set_tests_properties(s2n_bike_r2_kem_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_blob_test "/Users/pkz/s2n/bin/s2n_blob_test")
set_tests_properties(s2n_blob_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_cbc_verify_test "/Users/pkz/s2n/bin/s2n_cbc_verify_test")
set_tests_properties(s2n_cbc_verify_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_cert_chain_and_key_test "/Users/pkz/s2n/bin/s2n_cert_chain_and_key_test")
set_tests_properties(s2n_cert_chain_and_key_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_certificate_extensions_test "/Users/pkz/s2n/bin/s2n_certificate_extensions_test")
set_tests_properties(s2n_certificate_extensions_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_change_cipher_spec_test "/Users/pkz/s2n/bin/s2n_change_cipher_spec_test")
set_tests_properties(s2n_change_cipher_spec_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_choose_supported_group_test "/Users/pkz/s2n/bin/s2n_choose_supported_group_test")
set_tests_properties(s2n_choose_supported_group_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_cipher_suite_match_test "/Users/pkz/s2n/bin/s2n_cipher_suite_match_test")
set_tests_properties(s2n_cipher_suite_match_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_cleanup_test "/Users/pkz/s2n/bin/s2n_cleanup_test")
set_tests_properties(s2n_cleanup_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_client_alpn_extension_test "/Users/pkz/s2n/bin/s2n_client_alpn_extension_test")
set_tests_properties(s2n_client_alpn_extension_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_client_auth_handshake_test "/Users/pkz/s2n/bin/s2n_client_auth_handshake_test")
set_tests_properties(s2n_client_auth_handshake_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_client_cert_request_context_test "/Users/pkz/s2n/bin/s2n_client_cert_request_context_test")
set_tests_properties(s2n_client_cert_request_context_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_client_empty_cert_test "/Users/pkz/s2n/bin/s2n_client_empty_cert_test")
set_tests_properties(s2n_client_empty_cert_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_client_extensions_test "/Users/pkz/s2n/bin/s2n_client_extensions_test")
set_tests_properties(s2n_client_extensions_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_client_hello_recv_test "/Users/pkz/s2n/bin/s2n_client_hello_recv_test")
set_tests_properties(s2n_client_hello_recv_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_client_hello_test "/Users/pkz/s2n/bin/s2n_client_hello_test")
set_tests_properties(s2n_client_hello_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_client_key_share_extension_test "/Users/pkz/s2n/bin/s2n_client_key_share_extension_test")
set_tests_properties(s2n_client_key_share_extension_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_client_max_frag_len_extension_test "/Users/pkz/s2n/bin/s2n_client_max_frag_len_extension_test")
set_tests_properties(s2n_client_max_frag_len_extension_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_client_pq_kem_extension_test "/Users/pkz/s2n/bin/s2n_client_pq_kem_extension_test")
set_tests_properties(s2n_client_pq_kem_extension_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_client_record_version_test "/Users/pkz/s2n/bin/s2n_client_record_version_test")
set_tests_properties(s2n_client_record_version_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_client_renegotiation_info_extension_test "/Users/pkz/s2n/bin/s2n_client_renegotiation_info_extension_test")
set_tests_properties(s2n_client_renegotiation_info_extension_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_client_sct_list_extension_test "/Users/pkz/s2n/bin/s2n_client_sct_list_extension_test")
set_tests_properties(s2n_client_sct_list_extension_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_client_secure_renegotiation_test "/Users/pkz/s2n/bin/s2n_client_secure_renegotiation_test")
set_tests_properties(s2n_client_secure_renegotiation_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_client_server_name_extension_test "/Users/pkz/s2n/bin/s2n_client_server_name_extension_test")
set_tests_properties(s2n_client_server_name_extension_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_client_session_ticket_extension_test "/Users/pkz/s2n/bin/s2n_client_session_ticket_extension_test")
set_tests_properties(s2n_client_session_ticket_extension_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_client_signature_algorithms_extension_test "/Users/pkz/s2n/bin/s2n_client_signature_algorithms_extension_test")
set_tests_properties(s2n_client_signature_algorithms_extension_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_client_status_request_extension_test "/Users/pkz/s2n/bin/s2n_client_status_request_extension_test")
set_tests_properties(s2n_client_status_request_extension_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_client_supported_groups_extension_test "/Users/pkz/s2n/bin/s2n_client_supported_groups_extension_test")
set_tests_properties(s2n_client_supported_groups_extension_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_client_supported_versions_extension_test "/Users/pkz/s2n/bin/s2n_client_supported_versions_extension_test")
set_tests_properties(s2n_client_supported_versions_extension_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_config_test "/Users/pkz/s2n/bin/s2n_config_test")
set_tests_properties(s2n_config_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_connection_context_test "/Users/pkz/s2n/bin/s2n_connection_context_test")
set_tests_properties(s2n_connection_context_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_connection_preferences_test "/Users/pkz/s2n/bin/s2n_connection_preferences_test")
set_tests_properties(s2n_connection_preferences_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_connection_test "/Users/pkz/s2n/bin/s2n_connection_test")
set_tests_properties(s2n_connection_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_drain_alert_test "/Users/pkz/s2n/bin/s2n_drain_alert_test")
set_tests_properties(s2n_drain_alert_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_drbg_test "/Users/pkz/s2n/bin/s2n_drbg_test")
set_tests_properties(s2n_drbg_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_ecc_evp_test "/Users/pkz/s2n/bin/s2n_ecc_evp_test")
set_tests_properties(s2n_ecc_evp_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_ecc_point_format_extension_test "/Users/pkz/s2n/bin/s2n_ecc_point_format_extension_test")
set_tests_properties(s2n_ecc_point_format_extension_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_ecdsa_test "/Users/pkz/s2n/bin/s2n_ecdsa_test")
set_tests_properties(s2n_ecdsa_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_encrypted_extensions_test "/Users/pkz/s2n/bin/s2n_encrypted_extensions_test")
set_tests_properties(s2n_encrypted_extensions_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_error_lookup_test "/Users/pkz/s2n/bin/s2n_error_lookup_test")
set_tests_properties(s2n_error_lookup_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_error_type_test "/Users/pkz/s2n/bin/s2n_error_type_test")
set_tests_properties(s2n_error_type_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_extension_list_parse_test "/Users/pkz/s2n/bin/s2n_extension_list_parse_test")
set_tests_properties(s2n_extension_list_parse_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_extension_list_process_test "/Users/pkz/s2n/bin/s2n_extension_list_process_test")
set_tests_properties(s2n_extension_list_process_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_extension_list_send_test "/Users/pkz/s2n/bin/s2n_extension_list_send_test")
set_tests_properties(s2n_extension_list_send_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_extension_type_lists_test "/Users/pkz/s2n/bin/s2n_extension_type_lists_test")
set_tests_properties(s2n_extension_type_lists_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_extension_type_test "/Users/pkz/s2n/bin/s2n_extension_type_test")
set_tests_properties(s2n_extension_type_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_extensions_server_key_share_select_test "/Users/pkz/s2n/bin/s2n_extensions_server_key_share_select_test")
set_tests_properties(s2n_extensions_server_key_share_select_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_fragmentation_coalescing_test "/Users/pkz/s2n/bin/s2n_fragmentation_coalescing_test")
set_tests_properties(s2n_fragmentation_coalescing_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_handshake_errno_test "/Users/pkz/s2n/bin/s2n_handshake_errno_test")
set_tests_properties(s2n_handshake_errno_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_handshake_test "/Users/pkz/s2n/bin/s2n_handshake_test")
set_tests_properties(s2n_handshake_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_hash_test "/Users/pkz/s2n/bin/s2n_hash_test")
set_tests_properties(s2n_hash_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_hkdf_test "/Users/pkz/s2n/bin/s2n_hkdf_test")
set_tests_properties(s2n_hkdf_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_hmac_test "/Users/pkz/s2n/bin/s2n_hmac_test")
set_tests_properties(s2n_hmac_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_hybrid_ecdhe_bike_r1_test "/Users/pkz/s2n/bin/s2n_hybrid_ecdhe_bike_r1_test")
set_tests_properties(s2n_hybrid_ecdhe_bike_r1_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_hybrid_ecdhe_bike_r2_test "/Users/pkz/s2n/bin/s2n_hybrid_ecdhe_bike_r2_test")
set_tests_properties(s2n_hybrid_ecdhe_bike_r2_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_hybrid_ecdhe_sike_r1_test "/Users/pkz/s2n/bin/s2n_hybrid_ecdhe_sike_r1_test")
set_tests_properties(s2n_hybrid_ecdhe_sike_r1_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_hybrid_ecdhe_sike_r2_test "/Users/pkz/s2n/bin/s2n_hybrid_ecdhe_sike_r2_test")
set_tests_properties(s2n_hybrid_ecdhe_sike_r2_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_kem_test "/Users/pkz/s2n/bin/s2n_kem_test")
set_tests_properties(s2n_kem_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_kex_test "/Users/pkz/s2n/bin/s2n_kex_test")
set_tests_properties(s2n_kex_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_kex_with_kem_test "/Users/pkz/s2n/bin/s2n_kex_with_kem_test")
set_tests_properties(s2n_kex_with_kem_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_key_share_extension_test "/Users/pkz/s2n/bin/s2n_key_share_extension_test")
set_tests_properties(s2n_key_share_extension_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_key_update_test "/Users/pkz/s2n/bin/s2n_key_update_test")
set_tests_properties(s2n_key_update_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_kyber_r2_kat_test "/Users/pkz/s2n/bin/s2n_kyber_r2_kat_test")
set_tests_properties(s2n_kyber_r2_kat_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_kyber_r2_kem_test "/Users/pkz/s2n/bin/s2n_kyber_r2_kem_test")
set_tests_properties(s2n_kyber_r2_kem_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_malformed_handshake_test "/Users/pkz/s2n/bin/s2n_malformed_handshake_test")
set_tests_properties(s2n_malformed_handshake_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_map_test "/Users/pkz/s2n/bin/s2n_map_test")
set_tests_properties(s2n_map_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_mem_allocator_test "/Users/pkz/s2n/bin/s2n_mem_allocator_test")
set_tests_properties(s2n_mem_allocator_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_mem_usage_test "/Users/pkz/s2n/bin/s2n_mem_usage_test")
set_tests_properties(s2n_mem_usage_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_mutual_auth_test "/Users/pkz/s2n/bin/s2n_mutual_auth_test")
set_tests_properties(s2n_mutual_auth_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_optional_client_auth_test "/Users/pkz/s2n/bin/s2n_optional_client_auth_test")
set_tests_properties(s2n_optional_client_auth_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_override_openssl_random_test "/Users/pkz/s2n/bin/s2n_override_openssl_random_test")
set_tests_properties(s2n_override_openssl_random_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_parse_client_supported_groups_list_test "/Users/pkz/s2n/bin/s2n_parse_client_supported_groups_list_test")
set_tests_properties(s2n_parse_client_supported_groups_list_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_pem_rsa_dhe_test "/Users/pkz/s2n/bin/s2n_pem_rsa_dhe_test")
set_tests_properties(s2n_pem_rsa_dhe_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_pem_test "/Users/pkz/s2n/bin/s2n_pem_test")
set_tests_properties(s2n_pem_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_pq_asm_noop_test "/Users/pkz/s2n/bin/s2n_pq_asm_noop_test")
set_tests_properties(s2n_pq_asm_noop_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_random_test "/Users/pkz/s2n/bin/s2n_random_test")
set_tests_properties(s2n_random_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_rc4_test "/Users/pkz/s2n/bin/s2n_rc4_test")
set_tests_properties(s2n_rc4_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_record_size_test "/Users/pkz/s2n/bin/s2n_record_size_test")
set_tests_properties(s2n_record_size_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_record_test "/Users/pkz/s2n/bin/s2n_record_test")
set_tests_properties(s2n_record_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_release_non_empty_buffers_test "/Users/pkz/s2n/bin/s2n_release_non_empty_buffers_test")
set_tests_properties(s2n_release_non_empty_buffers_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_rfc5952_test "/Users/pkz/s2n/bin/s2n_rfc5952_test")
set_tests_properties(s2n_rfc5952_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_rsa_pss_rsae_test "/Users/pkz/s2n/bin/s2n_rsa_pss_rsae_test")
set_tests_properties(s2n_rsa_pss_rsae_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_rsa_pss_test "/Users/pkz/s2n/bin/s2n_rsa_pss_test")
set_tests_properties(s2n_rsa_pss_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_safety_test "/Users/pkz/s2n/bin/s2n_safety_test")
set_tests_properties(s2n_safety_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_security_policies_test "/Users/pkz/s2n/bin/s2n_security_policies_test")
set_tests_properties(s2n_security_policies_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_self_talk_alerts_test "/Users/pkz/s2n/bin/s2n_self_talk_alerts_test")
set_tests_properties(s2n_self_talk_alerts_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_self_talk_alpn_test "/Users/pkz/s2n/bin/s2n_self_talk_alpn_test")
set_tests_properties(s2n_self_talk_alpn_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_self_talk_broken_pipe_test "/Users/pkz/s2n/bin/s2n_self_talk_broken_pipe_test")
set_tests_properties(s2n_self_talk_broken_pipe_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_self_talk_client_hello_cb_test "/Users/pkz/s2n/bin/s2n_self_talk_client_hello_cb_test")
set_tests_properties(s2n_self_talk_client_hello_cb_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_self_talk_custom_io_test "/Users/pkz/s2n/bin/s2n_self_talk_custom_io_test")
set_tests_properties(s2n_self_talk_custom_io_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_self_talk_min_protocol_version_test "/Users/pkz/s2n/bin/s2n_self_talk_min_protocol_version_test")
set_tests_properties(s2n_self_talk_min_protocol_version_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_self_talk_nonblocking_test "/Users/pkz/s2n/bin/s2n_self_talk_nonblocking_test")
set_tests_properties(s2n_self_talk_nonblocking_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_self_talk_session_id_test "/Users/pkz/s2n/bin/s2n_self_talk_session_id_test")
set_tests_properties(s2n_self_talk_session_id_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_self_talk_test "/Users/pkz/s2n/bin/s2n_self_talk_test")
set_tests_properties(s2n_self_talk_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_self_talk_tls13_test "/Users/pkz/s2n/bin/s2n_self_talk_tls13_test")
set_tests_properties(s2n_self_talk_tls13_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_server_alpn_extension_test "/Users/pkz/s2n/bin/s2n_server_alpn_extension_test")
set_tests_properties(s2n_server_alpn_extension_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_server_certificate_status_test "/Users/pkz/s2n/bin/s2n_server_certificate_status_test")
set_tests_properties(s2n_server_certificate_status_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_server_extensions_test "/Users/pkz/s2n/bin/s2n_server_extensions_test")
set_tests_properties(s2n_server_extensions_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_server_hello_retry_test "/Users/pkz/s2n/bin/s2n_server_hello_retry_test")
set_tests_properties(s2n_server_hello_retry_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_server_hello_test "/Users/pkz/s2n/bin/s2n_server_hello_test")
set_tests_properties(s2n_server_hello_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_server_key_share_extension_test "/Users/pkz/s2n/bin/s2n_server_key_share_extension_test")
set_tests_properties(s2n_server_key_share_extension_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_server_max_frag_len_extension_test "/Users/pkz/s2n/bin/s2n_server_max_frag_len_extension_test")
set_tests_properties(s2n_server_max_frag_len_extension_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_server_renegotiation_info_test "/Users/pkz/s2n/bin/s2n_server_renegotiation_info_test")
set_tests_properties(s2n_server_renegotiation_info_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_server_sct_list_extension_test "/Users/pkz/s2n/bin/s2n_server_sct_list_extension_test")
set_tests_properties(s2n_server_sct_list_extension_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_server_server_name_extension_test "/Users/pkz/s2n/bin/s2n_server_server_name_extension_test")
set_tests_properties(s2n_server_server_name_extension_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_server_session_ticket_extension_test "/Users/pkz/s2n/bin/s2n_server_session_ticket_extension_test")
set_tests_properties(s2n_server_session_ticket_extension_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_server_signature_algorithms_extension_test "/Users/pkz/s2n/bin/s2n_server_signature_algorithms_extension_test")
set_tests_properties(s2n_server_signature_algorithms_extension_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_server_status_request_extension_test "/Users/pkz/s2n/bin/s2n_server_status_request_extension_test")
set_tests_properties(s2n_server_status_request_extension_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_server_supported_versions_extension_test "/Users/pkz/s2n/bin/s2n_server_supported_versions_extension_test")
set_tests_properties(s2n_server_supported_versions_extension_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_session_ticket_test "/Users/pkz/s2n/bin/s2n_session_ticket_test")
set_tests_properties(s2n_session_ticket_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_set_test "/Users/pkz/s2n/bin/s2n_set_test")
set_tests_properties(s2n_set_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_signature_algorithms_test "/Users/pkz/s2n/bin/s2n_signature_algorithms_test")
set_tests_properties(s2n_signature_algorithms_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_sike_r1_kat_test "/Users/pkz/s2n/bin/s2n_sike_r1_kat_test")
set_tests_properties(s2n_sike_r1_kat_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_sike_r1_kem_test "/Users/pkz/s2n/bin/s2n_sike_r1_kem_test")
set_tests_properties(s2n_sike_r1_kem_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_sike_r2_kat_test "/Users/pkz/s2n/bin/s2n_sike_r2_kat_test")
set_tests_properties(s2n_sike_r2_kat_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_sike_r2_kem_test "/Users/pkz/s2n/bin/s2n_sike_r2_kem_test")
set_tests_properties(s2n_sike_r2_kem_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_ssl_prf_test "/Users/pkz/s2n/bin/s2n_ssl_prf_test")
set_tests_properties(s2n_ssl_prf_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_stacktrace_test "/Users/pkz/s2n/bin/s2n_stacktrace_test")
set_tests_properties(s2n_stacktrace_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_str_test "/Users/pkz/s2n/bin/s2n_str_test")
set_tests_properties(s2n_str_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_stuffer_base64_test "/Users/pkz/s2n/bin/s2n_stuffer_base64_test")
set_tests_properties(s2n_stuffer_base64_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_stuffer_hex_test "/Users/pkz/s2n/bin/s2n_stuffer_hex_test")
set_tests_properties(s2n_stuffer_hex_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_stuffer_network_order_test "/Users/pkz/s2n/bin/s2n_stuffer_network_order_test")
set_tests_properties(s2n_stuffer_network_order_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_stuffer_test "/Users/pkz/s2n/bin/s2n_stuffer_test")
set_tests_properties(s2n_stuffer_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_stuffer_text_test "/Users/pkz/s2n/bin/s2n_stuffer_text_test")
set_tests_properties(s2n_stuffer_text_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_timer_test "/Users/pkz/s2n/bin/s2n_timer_test")
set_tests_properties(s2n_timer_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_tls12_handshake_test "/Users/pkz/s2n/bin/s2n_tls12_handshake_test")
set_tests_properties(s2n_tls12_handshake_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_tls13_cert_request_extensions_test "/Users/pkz/s2n/bin/s2n_tls13_cert_request_extensions_test")
set_tests_properties(s2n_tls13_cert_request_extensions_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_tls13_cert_request_test "/Users/pkz/s2n/bin/s2n_tls13_cert_request_test")
set_tests_properties(s2n_tls13_cert_request_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_tls13_cert_verify_test "/Users/pkz/s2n/bin/s2n_tls13_cert_verify_test")
set_tests_properties(s2n_tls13_cert_verify_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_tls13_client_finished_test "/Users/pkz/s2n/bin/s2n_tls13_client_finished_test")
set_tests_properties(s2n_tls13_client_finished_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_tls13_compute_shared_secret_test "/Users/pkz/s2n/bin/s2n_tls13_compute_shared_secret_test")
set_tests_properties(s2n_tls13_compute_shared_secret_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_tls13_cookie_test "/Users/pkz/s2n/bin/s2n_tls13_cookie_test")
set_tests_properties(s2n_tls13_cookie_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_tls13_handshake_test "/Users/pkz/s2n/bin/s2n_tls13_handshake_test")
set_tests_properties(s2n_tls13_handshake_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_tls13_keys_test "/Users/pkz/s2n/bin/s2n_tls13_keys_test")
set_tests_properties(s2n_tls13_keys_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_tls13_parse_record_type_test "/Users/pkz/s2n/bin/s2n_tls13_parse_record_type_test")
set_tests_properties(s2n_tls13_parse_record_type_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_tls13_prf_test "/Users/pkz/s2n/bin/s2n_tls13_prf_test")
set_tests_properties(s2n_tls13_prf_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_tls13_record_aead_test "/Users/pkz/s2n/bin/s2n_tls13_record_aead_test")
set_tests_properties(s2n_tls13_record_aead_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_tls13_server_cert_test "/Users/pkz/s2n/bin/s2n_tls13_server_cert_test")
set_tests_properties(s2n_tls13_server_cert_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_tls13_server_finished_test "/Users/pkz/s2n/bin/s2n_tls13_server_finished_test")
set_tests_properties(s2n_tls13_server_finished_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_tls13_state_machine_handshake_test "/Users/pkz/s2n/bin/s2n_tls13_state_machine_handshake_test")
set_tests_properties(s2n_tls13_state_machine_handshake_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_tls13_support_test "/Users/pkz/s2n/bin/s2n_tls13_support_test")
set_tests_properties(s2n_tls13_support_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_tls13_zero_length_payload_test "/Users/pkz/s2n/bin/s2n_tls13_zero_length_payload_test")
set_tests_properties(s2n_tls13_zero_length_payload_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_tls_hybrid_prf_test "/Users/pkz/s2n/bin/s2n_tls_hybrid_prf_test")
set_tests_properties(s2n_tls_hybrid_prf_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_tls_prf_test "/Users/pkz/s2n/bin/s2n_tls_prf_test")
set_tests_properties(s2n_tls_prf_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_tls_record_stuffer_test "/Users/pkz/s2n/bin/s2n_tls_record_stuffer_test")
set_tests_properties(s2n_tls_record_stuffer_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_utils_test "/Users/pkz/s2n/bin/s2n_utils_test")
set_tests_properties(s2n_utils_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_wildcard_hostname_test "/Users/pkz/s2n/bin/s2n_wildcard_hostname_test")
set_tests_properties(s2n_wildcard_hostname_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
add_test(s2n_x509_validator_test "/Users/pkz/s2n/bin/s2n_x509_validator_test")
set_tests_properties(s2n_x509_validator_test PROPERTIES  ENVIRONMENT "S2N_DONT_MLOCK=1" WORKING_DIRECTORY "/Users/pkz/s2n/tests/unit" _BACKTRACE_TRIPLES "/Users/pkz/s2n/CMakeLists.txt;263;add_test;/Users/pkz/s2n/CMakeLists.txt;0;")
