/* automatically generated by rust-bindgen 0.58.1 */


// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0


#![allow(unused_imports, non_camel_case_types)]

use libc::{iovec, FILE};

use crate::api::*;


extern "C" {
    pub fn s2n_connection_get_config(
        conn: *mut s2n_connection,
        config: *mut *mut s2n_config,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn s2n_config_add_cert_chain(
        config: *mut s2n_config,
        cert_chain_pem: *mut u8,
        cert_chain_pem_size: u32,
    ) -> ::libc::c_int;
}
