#!/usr/bin/env bash

#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

set -e

if ! command -v "inferno-collapse-perf" &> /dev/null; then
  cargo install inferno
fi

